@startuml
!include Style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteProjectCommandParser" as DeleteProjectCommandParser LOGIC_COLOR
participant "d:DeleteProjectCommand" as DeleteProjectCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as Model MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
participant ":UniqueProjectList" as UniqueProjectList MODEL_COLOR
participant ":UniqueClientList" as UniqueClientList MODEL_COLOR
participant ":UniqueDeveloperList" as UniqueDeveloperList MODEL_COLOR
end box

[-> LogicManager : execute("delete-project 2")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete-project 2")
activate AddressBookParser

create DeleteProjectCommandParser
AddressBookParser -> DeleteProjectCommandParser
activate DeleteProjectCommandParser

DeleteProjectCommandParser --> AddressBookParser
deactivate DeleteProjectCommandParser

AddressBookParser -> DeleteProjectCommandParser : parse("2")
activate DeleteProjectCommandParser

create DeleteProjectCommand
DeleteProjectCommandParser -> DeleteProjectCommand
activate DeleteProjectCommand

DeleteProjectCommand --> DeleteProjectCommandParser : d
deactivate DeleteProjectCommand

DeleteProjectCommandParser --> AddressBookParser : d
deactivate DeleteProjectCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteProjectCommandParser -[hidden]-> AddressBookParser
destroy DeleteProjectCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteProjectCommand : execute()
activate DeleteProjectCommand

DeleteProjectCommand -> Model : deleteProject(2)
activate Model

Model -> AddressBook : removeProject(2)
activate AddressBook

AddressBook -> UniqueProjectList : remove(2)
activate UniqueProjectList
UniqueProjectList --> AddressBook
deactivate UniqueProjectList
AddressBook -> UniqueClientList : updateClientProjects("2")
activate UniqueClientList
UniqueClientList --> AddressBook
deactivate UniqueClientList
AddressBook -> UniqueDeveloperList : updateClientProjects("2")
activate UniqueDeveloperList
UniqueDeveloperList --> AddressBook
deactivate UniqueDeveloperList
AddressBook --> Model
deactivate AddressBook


Model --> DeleteProjectCommand
deactivate Model

create CommandResult
DeleteProjectCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteProjectCommand
deactivate CommandResult

DeleteProjectCommand --> LogicManager : result
deactivate DeleteProjectCommand

[<--LogicManager
deactivate LogicManager
@enduml